export default {
  products: [
    {
      id: "1",
      name: "Women Color-block Sneakers",
      title: "Sneakers & Ked",
      image: "./src/public/image/shop/catalog/01.jpg",
      price: "154.00",
      categoryId: "0",
      status: true,
      quantity: 82,
    },
    {
      id: "2",
      name: "Cotton Lace Blouse",
      title: "Women's T-shift",
      image: "./src/public/image/shop/catalog/02.jpg",
      price: "28.50",
      categoryId: "1",
      status: true,
      quantity: 57,
    },
    {
      id: "3",
      name: "Mom Hight Waist Shorts",
      title: "Women's Shorts",
      image: "./src/public/image/shop/catalog/03.jpg",
      price: "39.50",
      categoryId: "1",
      status: true,
      quantity: 51,
    },
    {
      id: "4",
      name: "Women Sports Jacket",
      title: "Sportswear",
      image: "./src/public/image/shop/catalog/04.jpg",
      price: "68.40",
      categoryId: "1",
      status: true,
      quantity: 56,
    },
    {
      id: "5",
      name: "Polarized Sunglasses",
      title: "Men's Sunglasses",
      image: "./src/public/image/shop/catalog/05.jpg",
      price: "14.20",
      categoryId: "3",
      status: false,
      quantity: 0,
    },
    {
      id: "6",
      name: "TH Jeans City Backpack",
      title: "Backpacks",
      image: "./src/public/image/shop/catalog/06.jpg",
      price: "79.50",
      categoryId: "0",
      status: true,
      quantity: 26,
    },
  ],
}